#!/usr/bin/env bash
#
# Render this deployment's loader overlays from the environment, then start the
# gateway.
#
# The overlays are generated rather than copied because the committed ones
# (`plugins/*.overlay.yml`) carry one machine's absolute paths and one realm's
# issuer. Everything path-shaped is fixed by the image layout; everything
# deployment-shaped is an environment variable, validated here so a missing
# value is a startup error rather than an opaque OIDC failure later.
set -euo pipefail

RENDER_DIR=${COMPLIANCE_RENDER_DIR:-/run/compliance-ai}
HARNESS_ROOT=${COMPLIANCE_HARNESS_ROOT:-/app}
USERS_ROOT=${COMPLIANCE_USERS_ROOT:-/var/lib/compliance-ai/users}
TENANCY=${COMPLIANCE_TENANCY:-on}
ALMA=${ALMA_ENABLED:-on}

# Overlays a per-user BACKEND must read cannot live in $RENDER_DIR: the bwrap
# jail binds only the node root, $HARNESS_ROOT and the user's own tree
# (plugins/compliance-tenancy/src/confine.ts), so a path under /run is simply
# absent inside it. This one directory is therefore rendered into the image
# tree, where the read-only bind makes it visible to every backend.
BACKEND_RENDER_DIR=$HARNESS_ROOT/.compliance-render

die() { printf 'compliance-entrypoint: %s\n' "$*" >&2; exit 1; }

# ── required configuration ────────────────────────────────────────────────────
missing=()
for var in SSO_ISSUER SSO_CLIENT_ID SSO_PUBLIC_URL; do
  [[ -n ${!var:-} ]] || missing+=("$var")
done
if (( ${#missing[@]} > 0 )); then
  die "missing required environment: ${missing[*]}
  SSO_ISSUER     OIDC issuer, e.g. https://sso.example.com/realms/Example
  SSO_CLIENT_ID  OAuth client id registered on that issuer
  SSO_PUBLIC_URL the origin browsers use; SSO_PUBLIC_URL/auth/callback must be
                 registered as a redirect URI on the client, exactly"
fi

# A confidential client is the default shape. The overlay names the VARIABLE,
# never the secret, so the value stays in the process environment only.
if [[ -n ${SSO_CLIENT_SECRET:-} ]]; then
  secret_line="clientSecretEnv: SSO_CLIENT_SECRET"
else
  secret_line="# public PKCE client: no clientSecretEnv"
fi

# Claim requirements. An empty value drops the block: no `require` admits every
# authenticated user, and no `admin` makes nobody an administrator — which is
# the safe direction, since the configuration plane is then closed to all.
SSO_REQUIRE_CLAIM_PATH=${SSO_REQUIRE_CLAIM_PATH:-resource_access.${SSO_CLIENT_ID}.roles}
SSO_ADMIN_CLAIM_PATH=${SSO_ADMIN_CLAIM_PATH:-resource_access.${SSO_CLIENT_ID}.roles}
SSO_REQUIRE_ROLES=${SSO_REQUIRE_ROLES-dsh-access}
SSO_ADMIN_ROLES=${SSO_ADMIN_ROLES-dsh-admin}

# Render a comma- or space-separated list as a YAML flow sequence.
yaml_list() {
  local raw=${1//,/ } out=() item
  for item in $raw; do out+=("$item"); done
  local joined
  joined=$(printf '%s, ' "${out[@]}")
  printf '[%s]' "${joined%, }"
}

# Render absolute paths as a YAML block sequence under a `config` key.
yaml_paths() {
  local path
  for path in "$@"; do printf '          - %s\n' "$path"; done
}

# A claim block, indented to sit under the sso-auth row's `config`.
claim_block() {
  local key=$1 path=$2 roles=$3
  [[ -n $roles ]] || return 0
  printf '        %s:\n          claimPath: %s\n          anyOf: %s\n' \
    "$key" "$path" "$(yaml_list "$roles")"
}

mkdir -p "$RENDER_DIR"
sso_overlay=$RENDER_DIR/sso-auth.overlay.yml
tenancy_overlay=$RENDER_DIR/compliance-tenancy.overlay.yml
alma_overlay=$BACKEND_RENDER_DIR/compliance-alma-mcp.overlay.yml

# ── the SSO gate ──────────────────────────────────────────────────────────────
#
# Both rows below matter as much as the insert: the webserver moves to an
# OS-assigned loopback port, and the runtime stops printing and opening the
# INTERNAL url — which under this composition is the ungated one.
{
  cat <<YAML
# Generated by compliance-entrypoint from the environment. Do not edit; the
# source of truth is deploy/docker/entrypoint.sh and the container environment.
- id: webserver
  config:
    host: 127.0.0.1
    port: 0

- id: web-runtime
  config:
    openBrowser: false
    printUrl: false
    surfaceContext: true
    trustedHosts: !!js ctx.webStartup.trustedHosts

- insert:
    - id: sso-auth
      name: '@compliance/dsh-sso-auth'
      inject: [webStartup]
      config:
        issuer: ${SSO_ISSUER}
        clientId: ${SSO_CLIENT_ID}
        ${secret_line}
        publicUrl: ${SSO_PUBLIC_URL}
        host: ${SSO_BIND_HOST:-0.0.0.0}
        port: ${SSO_PORT:-3080}
        scopes: $(yaml_list "${SSO_SCOPES:-openid profile email}")
YAML
  claim_block require "$SSO_REQUIRE_CLAIM_PATH" "$SSO_REQUIRE_ROLES"
  claim_block admin "$SSO_ADMIN_CLAIM_PATH" "$SSO_ADMIN_ROLES"
  cat <<YAML
        sessionTtlMinutes: ${SSO_SESSION_TTL_MINUTES:-480}
        idleTimeoutMinutes: ${SSO_IDLE_TIMEOUT_MINUTES:-60}
YAML
} > "$sso_overlay"

patches=("$sso_overlay")

# ── the ALMA MCP connection ───────────────────────────────────────────────────
#
# `publicUrl` is SSO_PUBLIC_URL and nothing else: the plugin builds its OAuth
# redirect URI from it, and ALMA will only return the browser to the origin the
# browser started from.
#
# A pinned client registration is optional. Given ALMA_CLIENT_ID, the row names
# the VARIABLE holding its secret rather than the secret, and that variable is
# forwarded into the jail below — without the forward, the backend would resolve
# it to nothing. Given neither, each workspace registers itself dynamically.
if [[ $ALMA == on ]]; then
  mkdir -p "$BACKEND_RENDER_DIR" 2>/dev/null \
    || die "could not create $BACKEND_RENDER_DIR; a backend cannot read an overlay outside $HARNESS_ROOT.
  Set ALMA_ENABLED=off, or make the image tree writable at start."

  {
    cat <<YAML
# Generated by compliance-entrypoint from the environment. Do not edit; the
# source of truth is deploy/docker/entrypoint.sh and the container environment.
- insert:
    - id: alma-mcp
      name: '@compliance/dsh-alma-mcp'
      inject: [webServer, credentials]
      config:
        mcpUrl: ${ALMA_MCP_URL:-https://mcp.compliancehcm.com.br/mcp}
        publicUrl: ${SSO_PUBLIC_URL}
        serverName: ${ALMA_SERVER_NAME:-alma}
        resolveMcpClientFrom: ${HARNESS_ROOT}/apps/cli
        scopes: $(yaml_list "${ALMA_SCOPES:-openid profile}")
        refreshSkewSeconds: ${ALMA_REFRESH_SKEW_SECONDS:-120}
YAML
    if [[ -n ${ALMA_CLIENT_ID:-} ]]; then
      printf '        clientId: %s\n' "$ALMA_CLIENT_ID"
      [[ -n ${ALMA_CLIENT_SECRET:-} ]] && printf '        clientSecretEnv: ALMA_CLIENT_SECRET\n'
    fi
  } > "$alma_overlay"

  # The plugin resolves the secret through the credential seam, which reads the
  # BACKEND's environment — so a pinned confidential client needs the variable
  # forwarded into the jail.
  if [[ -n ${ALMA_CLIENT_ID:-} && -n ${ALMA_CLIENT_SECRET:-} ]]; then
    COMPLIANCE_FORWARD_CREDENTIALS="${COMPLIANCE_FORWARD_CREDENTIALS:-DEEPSEEK_API_KEY} ALMA_CLIENT_SECRET"
  fi
else
  printf 'compliance-entrypoint: ALMA is OFF — no MCP connection to Compliance HCM is composed.\n' >&2
fi

# ── tenancy ───────────────────────────────────────────────────────────────────
if [[ $TENANCY == on ]]; then
  mkdir -p "$USERS_ROOT"
  if [[ ${COMPLIANCE_CONFINEMENT:-bwrap} != bwrap ]]; then
    printf 'compliance-entrypoint: WARNING confinement=%s — backends are NOT isolated from each other.\n' \
      "${COMPLIANCE_CONFINEMENT}" >&2
  fi
  # The backend composition, assembled as lists rather than written inline:
  # every row here is conditional on ALMA being composed, and one list read by
  # both roles is what keeps user and admin from drifting apart.
  backend_packages=(
    "$HARNESS_ROOT/plugins/compliance-brand"
    "$HARNESS_ROOT/plugins/compliance-user-menu"
  )
  backend_patches=(
    "$HARNESS_ROOT/plugins/compliance-brand.overlay.yml"
    "$HARNESS_ROOT/plugins/compliance-user-menu.overlay.yml"
  )
  if [[ $ALMA == on ]]; then
    backend_packages+=("$HARNESS_ROOT/plugins/compliance-alma-mcp")
    backend_patches+=("$alma_overlay")
  fi

  # forwardCredentials names variables resolved from the gateway's own
  # environment; the values are never written into this file.
  {
    cat <<YAML
# Generated by compliance-entrypoint from the environment. Do not edit.
- insert:
    - id: compliance-tenancy
      name: '@compliance/dsh-tenancy'
      config:
        usersRoot: ${USERS_ROOT}
        harnessRoot: ${HARNESS_ROOT}
        confinement: ${COMPLIANCE_CONFINEMENT:-bwrap}
        portRange: [${COMPLIANCE_PORT_RANGE_START:-31000}, ${COMPLIANCE_PORT_RANGE_END:-31200}]
        maxBackends: ${COMPLIANCE_MAX_BACKENDS:-12}
        idleReapMinutes: ${COMPLIANCE_IDLE_REAP_MINUTES:-15}
        forwardCredentials: $(yaml_list "${COMPLIANCE_FORWARD_CREDENTIALS:-DEEPSEEK_API_KEY}")
        pluginPackages:
YAML
    yaml_paths "${backend_packages[@]}"
    printf '        userPatches:\n'
    yaml_paths "${backend_patches[@]}" "$HARNESS_ROOT/plugins/compliance-tenancy/role-user.overlay.yml"
    printf '        adminPatches:\n'
    yaml_paths "${backend_patches[@]}" "$HARNESS_ROOT/plugins/compliance-tenancy/role-admin.overlay.yml"
  } > "$tenancy_overlay"
  patches+=("$tenancy_overlay")
else
  # Single-harness mode: no per-user backend, so the brand, user-menu and ALMA
  # rows belong to the gateway's own composition instead of to a backend's.
  printf 'compliance-entrypoint: tenancy is OFF — every signed-in user shares one harness and one workspace.\n' >&2
  patches+=(
    "$HARNESS_ROOT/plugins/compliance-brand.overlay.yml"
    "$HARNESS_ROOT/plugins/compliance-user-menu.overlay.yml"
  )
  [[ $ALMA == on ]] && patches+=("$alma_overlay")
fi

# ── launch ────────────────────────────────────────────────────────────────────
#
# The tsx source launch, not the built CLI: the gateway plugins are TypeScript.
# `--patch` is a launcher flag, so it precedes any app arguments.
args=()
for patch in "${patches[@]}"; do args+=(--patch "$patch"); done

printf 'compliance-entrypoint: gateway on %s:%s, public url %s\n' \
  "${SSO_BIND_HOST:-0.0.0.0}" "${SSO_PORT:-3080}" "$SSO_PUBLIC_URL" >&2

cd "$HARNESS_ROOT"
exec node --import tsx/esm "$HARNESS_ROOT/apps/cli/src/bin.ts" \
  --profile web "${args[@]}" "$@"
