#!/usr/bin/env bash
#
# Render this deployment's loader overlays from the environment, then start the
# gateway.
#
# The overlays are generated rather than copied because the committed ones
# (`plugins/*.overlay.yml`) carry one machine's absolute paths and one realm's
# issuer. Everything path-shaped is fixed by the image layout; everything
# deployment-shaped is an environment variable, validated here so a missing
# value is a startup error rather than an opaque OIDC failure later.
set -euo pipefail

RENDER_DIR=${COMPLIANCE_RENDER_DIR:-/run/compliance-ai}
HARNESS_ROOT=${COMPLIANCE_HARNESS_ROOT:-/app}
USERS_ROOT=${COMPLIANCE_USERS_ROOT:-/var/lib/compliance-ai/users}
TENANCY=${COMPLIANCE_TENANCY:-on}

die() { printf 'compliance-entrypoint: %s\n' "$*" >&2; exit 1; }

# ── required configuration ────────────────────────────────────────────────────
missing=()
for var in SSO_ISSUER SSO_CLIENT_ID SSO_PUBLIC_URL; do
  [[ -n ${!var:-} ]] || missing+=("$var")
done
if (( ${#missing[@]} > 0 )); then
  die "missing required environment: ${missing[*]}
  SSO_ISSUER     OIDC issuer, e.g. https://sso.example.com/realms/Example
  SSO_CLIENT_ID  OAuth client id registered on that issuer
  SSO_PUBLIC_URL the origin browsers use; SSO_PUBLIC_URL/auth/callback must be
                 registered as a redirect URI on the client, exactly"
fi

# A confidential client is the default shape. The overlay names the VARIABLE,
# never the secret, so the value stays in the process environment only.
if [[ -n ${SSO_CLIENT_SECRET:-} ]]; then
  secret_line="clientSecretEnv: SSO_CLIENT_SECRET"
else
  secret_line="# public PKCE client: no clientSecretEnv"
fi

# Claim requirements. An empty value drops the block: no `require` admits every
# authenticated user, and no `admin` makes nobody an administrator — which is
# the safe direction, since the configuration plane is then closed to all.
SSO_REQUIRE_CLAIM_PATH=${SSO_REQUIRE_CLAIM_PATH:-resource_access.${SSO_CLIENT_ID}.roles}
SSO_ADMIN_CLAIM_PATH=${SSO_ADMIN_CLAIM_PATH:-resource_access.${SSO_CLIENT_ID}.roles}
SSO_REQUIRE_ROLES=${SSO_REQUIRE_ROLES-dsh-access}
SSO_ADMIN_ROLES=${SSO_ADMIN_ROLES-dsh-admin}

# Render a comma- or space-separated list as a YAML flow sequence.
yaml_list() {
  local raw=${1//,/ } out=() item
  for item in $raw; do out+=("$item"); done
  local joined
  joined=$(printf '%s, ' "${out[@]}")
  printf '[%s]' "${joined%, }"
}

# A claim block, indented to sit under the sso-auth row's `config`.
claim_block() {
  local key=$1 path=$2 roles=$3
  [[ -n $roles ]] || return 0
  printf '        %s:\n          claimPath: %s\n          anyOf: %s\n' \
    "$key" "$path" "$(yaml_list "$roles")"
}

mkdir -p "$RENDER_DIR"
sso_overlay=$RENDER_DIR/sso-auth.overlay.yml
tenancy_overlay=$RENDER_DIR/compliance-tenancy.overlay.yml

# ── the SSO gate ──────────────────────────────────────────────────────────────
#
# Both rows below matter as much as the insert: the webserver moves to an
# OS-assigned loopback port, and the runtime stops printing and opening the
# INTERNAL url — which under this composition is the ungated one.
{
  cat <<YAML
# Generated by compliance-entrypoint from the environment. Do not edit; the
# source of truth is deploy/docker/entrypoint.sh and the container environment.
- id: webserver
  config:
    host: 127.0.0.1
    port: 0

- id: web-runtime
  config:
    openBrowser: false
    printUrl: false
    surfaceContext: true
    trustedHosts: !!js ctx.webStartup.trustedHosts

- insert:
    - id: sso-auth
      name: '@compliance/dsh-sso-auth'
      inject: [webStartup]
      config:
        issuer: ${SSO_ISSUER}
        clientId: ${SSO_CLIENT_ID}
        ${secret_line}
        publicUrl: ${SSO_PUBLIC_URL}
        host: ${SSO_BIND_HOST:-0.0.0.0}
        port: ${SSO_PORT:-3080}
        scopes: $(yaml_list "${SSO_SCOPES:-openid profile email}")
YAML
  claim_block require "$SSO_REQUIRE_CLAIM_PATH" "$SSO_REQUIRE_ROLES"
  claim_block admin "$SSO_ADMIN_CLAIM_PATH" "$SSO_ADMIN_ROLES"
  cat <<YAML
        sessionTtlMinutes: ${SSO_SESSION_TTL_MINUTES:-480}
        idleTimeoutMinutes: ${SSO_IDLE_TIMEOUT_MINUTES:-60}
YAML
} > "$sso_overlay"

patches=("$sso_overlay")

# ── tenancy ───────────────────────────────────────────────────────────────────
if [[ $TENANCY == on ]]; then
  mkdir -p "$USERS_ROOT"
  if [[ ${COMPLIANCE_CONFINEMENT:-bwrap} != bwrap ]]; then
    printf 'compliance-entrypoint: WARNING confinement=%s — backends are NOT isolated from each other.\n' \
      "${COMPLIANCE_CONFINEMENT}" >&2
  fi
  # forwardCredentials names variables resolved from the gateway's own
  # environment; the values are never written into this file.
  cat > "$tenancy_overlay" <<YAML
# Generated by compliance-entrypoint from the environment. Do not edit.
- insert:
    - id: compliance-tenancy
      name: '@compliance/dsh-tenancy'
      config:
        usersRoot: ${USERS_ROOT}
        harnessRoot: ${HARNESS_ROOT}
        confinement: ${COMPLIANCE_CONFINEMENT:-bwrap}
        portRange: [${COMPLIANCE_PORT_RANGE_START:-31000}, ${COMPLIANCE_PORT_RANGE_END:-31200}]
        maxBackends: ${COMPLIANCE_MAX_BACKENDS:-12}
        idleReapMinutes: ${COMPLIANCE_IDLE_REAP_MINUTES:-15}
        forwardCredentials: $(yaml_list "${COMPLIANCE_FORWARD_CREDENTIALS:-DEEPSEEK_API_KEY}")
        pluginPackages:
          - ${HARNESS_ROOT}/plugins/compliance-brand
          - ${HARNESS_ROOT}/plugins/compliance-user-menu
        userPatches:
          - ${HARNESS_ROOT}/plugins/compliance-brand.overlay.yml
          - ${HARNESS_ROOT}/plugins/compliance-user-menu.overlay.yml
          - ${HARNESS_ROOT}/plugins/compliance-tenancy/role-user.overlay.yml
        adminPatches:
          - ${HARNESS_ROOT}/plugins/compliance-brand.overlay.yml
          - ${HARNESS_ROOT}/plugins/compliance-user-menu.overlay.yml
          - ${HARNESS_ROOT}/plugins/compliance-tenancy/role-admin.overlay.yml
YAML
  patches+=("$tenancy_overlay")
else
  # Single-harness mode: no per-user backend, so the brand and user-menu rows
  # belong to the gateway's own composition instead of to a backend's.
  printf 'compliance-entrypoint: tenancy is OFF — every signed-in user shares one harness and one workspace.\n' >&2
  patches+=(
    "$HARNESS_ROOT/plugins/compliance-brand.overlay.yml"
    "$HARNESS_ROOT/plugins/compliance-user-menu.overlay.yml"
  )
fi

# ── launch ────────────────────────────────────────────────────────────────────
#
# The tsx source launch, not the built CLI: the gateway plugins are TypeScript.
# `--patch` is a launcher flag, so it precedes any app arguments.
args=()
for patch in "${patches[@]}"; do args+=(--patch "$patch"); done

printf 'compliance-entrypoint: gateway on %s:%s, public url %s\n' \
  "${SSO_BIND_HOST:-0.0.0.0}" "${SSO_PORT:-3080}" "$SSO_PUBLIC_URL" >&2

cd "$HARNESS_ROOT"
exec node --import tsx/esm "$HARNESS_ROOT/apps/cli/src/bin.ts" \
  --profile web "${args[@]}" "$@"
