{{- if and (not .Values.secrets.existingSecret) .Values.secrets.values }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "compliance-ai.fullname" . }}
  labels:
    {{- include "compliance-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.values }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
